//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIM.IFC.Export.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BIM.IFC.Export.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase to export.
        /// </summary>
        public static string ActivePhase {
            get {
                return ResourceManager.GetString("ActivePhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 1.
        /// </summary>
        public static string AddressLine1 {
            get {
                return ResourceManager.GetString("AddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 2.
        /// </summary>
        public static string AddressLine2 {
            get {
                return ResourceManager.GetString("AddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate UI.
        /// </summary>
        public static string AltUIVer {
            get {
                return ResourceManager.GetString("AltUIVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application name.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments....
        /// </summary>
        public static string Assignments {
            get {
                return ResourceManager.GetString("Assignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        public static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author&apos;s email.
        /// </summary>
        public static string AuthorsEMail {
            get {
                return ResourceManager.GetString("AuthorsEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author&apos;s name.
        /// </summary>
        public static string AuthorsName {
            get {
                return ResourceManager.GetString("AuthorsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse ....
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification.
        /// </summary>
        public static string Classification {
            get {
                return ResourceManager.GetString("Classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The optional alternate shared parameter name for this classification (default: ClassificationCode).
        /// </summary>
        public static string ClassificationAltName {
            get {
                return ResourceManager.GetString("ClassificationAltName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification field name.
        /// </summary>
        public static string ClassificationFieldName {
            get {
                return ResourceManager.GetString("ClassificationFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition number of the Classification system.
        /// </summary>
        public static string ClassificationSystemEdition {
            get {
                return ResourceManager.GetString("ClassificationSystemEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the Classification System.
        /// </summary>
        public static string ClassificationSystemName {
            get {
                return ResourceManager.GetString("ClassificationSystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source or publisher of the Classification System.
        /// </summary>
        public static string ClassificationSystemSource {
            get {
                return ResourceManager.GetString("ClassificationSystemSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new setup based on the selected setup..
        /// </summary>
        public static string CloneSetup {
            get {
                return ResourceManager.GetString("CloneSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new setup..
        /// </summary>
        public static string CreateNewSetup {
            get {
                return ResourceManager.GetString("CreateNewSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current selected setup.
        /// </summary>
        public static string CurrentSelectedSetup {
            get {
                return ResourceManager.GetString("CurrentSelectedSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default ({0}).
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default phase to export.
        /// </summary>
        public static string DefaultPhase {
            get {
                return ResourceManager.GetString("DefaultPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete old IFC export setups.
        /// </summary>
        public static string DeleteOldSetups {
            get {
                return ResourceManager.GetString("DeleteOldSetups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the selected setup..
        /// </summary>
        public static string DeleteSelectedSetup {
            get {
                return ResourceManager.GetString("DeleteSelectedSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Point.
        /// </summary>
        public static string DistributionPoint {
            get {
                return ResourceManager.GetString("DistributionPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation location.
        /// </summary>
        public static string DocumentationLocation {
            get {
                return ResourceManager.GetString("DocumentationLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t {0}.
        /// </summary>
        public static string Dont {
            get {
                return ResourceManager.GetString("Dont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition.
        /// </summary>
        public static string Edition {
            get {
                return ResourceManager.GetString("Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition date.
        /// </summary>
        public static string EditionDate {
            get {
                return ResourceManager.GetString("EditionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export….
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export base quantities.
        /// </summary>
        public static string ExportBaseQuantities {
            get {
                return ResourceManager.GetString("ExportBaseQuantities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export bounding box.
        /// </summary>
        public static string ExportBoundingBox {
            get {
                return ResourceManager.GetString("ExportBoundingBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export only elements visible in view.
        /// </summary>
        public static string ExportElementsVisibleInView {
            get {
                return ResourceManager.GetString("ExportElementsVisibleInView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export IFC common property sets.
        /// </summary>
        public static string ExportIFCCommonPropertySets {
            get {
                return ResourceManager.GetString("ExportIFCCommonPropertySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export internal Revit property sets.
        /// </summary>
        public static string ExportInternalRevitPropertySets {
            get {
                return ResourceManager.GetString("ExportInternalRevitPropertySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export linked files as separate IFCs.
        /// </summary>
        public static string ExportLinkedFiles {
            get {
                return ResourceManager.GetString("ExportLinkedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export parts as building elements.
        /// </summary>
        public static string ExportPartsAsBuildingElements {
            get {
                return ResourceManager.GetString("ExportPartsAsBuildingElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export 2D plan view elements.
        /// </summary>
        public static string ExportPlanViewElements {
            get {
                return ResourceManager.GetString("ExportPlanViewElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Revit property sets.
        /// </summary>
        public static string ExportRevitPropertySets {
            get {
                return ResourceManager.GetString("ExportRevitPropertySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export schedules as property sets.
        /// </summary>
        public static string ExportSchedulesAsPropertySets {
            get {
                return ResourceManager.GetString("ExportSchedulesAsPropertySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export schedules as property sets.
        /// </summary>
        public static string ExportSchedulesAsPsets {
            get {
                return ResourceManager.GetString("ExportSchedulesAsPsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export solid models when possible.
        /// </summary>
        public static string ExportSolidModelRep {
            get {
                return ResourceManager.GetString("ExportSolidModelRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export solid models when possible.
        /// </summary>
        public static string ExportSolidModelsWhenPossible {
            get {
                return ResourceManager.GetString("ExportSolidModelsWhenPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export user defined property sets.
        /// </summary>
        public static string ExportUserDefinedPropertySets {
            get {
                return ResourceManager.GetString("ExportUserDefinedPropertySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export user-defined property sets.
        /// </summary>
        public static string ExportUserDefinedPsets {
            get {
                return ResourceManager.GetString("ExportUserDefinedPsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-defined property set file name.
        /// </summary>
        public static string ExportUserDefinedPsetsFileName {
            get {
                return ResourceManager.GetString("ExportUserDefinedPsetsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export only elements visible in view.
        /// </summary>
        public static string ExportVisibleElementsInView {
            get {
                return ResourceManager.GetString("ExportVisibleElementsInView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File description.
        /// </summary>
        public static string FileDescription {
            get {
                return ResourceManager.GetString("FileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File header.
        /// </summary>
        public static string FileHeader {
            get {
                return ResourceManager.GetString("FileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File schema.
        /// </summary>
        public static string FileSchema {
            get {
                return ResourceManager.GetString("FileSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type.
        /// </summary>
        public static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File version.
        /// </summary>
        public static string FileVersion {
            get {
                return ResourceManager.GetString("FileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC.
        /// </summary>
        public static string IFC {
            get {
                return ResourceManager.GetString("IFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC Assignments.
        /// </summary>
        public static string IFCAssignments {
            get {
                return ResourceManager.GetString("IFCAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC export.
        /// </summary>
        public static string IFCExport {
            get {
                return ResourceManager.GetString("IFCExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IFC export process encountered an error..
        /// </summary>
        public static string IFCExportProcessError {
            get {
                return ResourceManager.GetString("IFCExportProcessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ifc.
        /// </summary>
        public static string IFCExt {
            get {
                return ResourceManager.GetString("IFCExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC-SPF|*.ifc.
        /// </summary>
        public static string IFCFiles {
            get {
                return ResourceManager.GetString("IFCFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC 2x3 Coordination View 2.0.
        /// </summary>
        public static string IFCMVD2x3CV2 {
            get {
                return ResourceManager.GetString("IFCMVD2x3CV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC 4 Coordination View 2.0.
        /// </summary>
        public static string IFCMVD4CV2 {
            get {
                return ResourceManager.GetString("IFCMVD4CV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC 2x2 Singapore BCA e-Plan Check.
        /// </summary>
        public static string IFCMVDBCA {
            get {
                return ResourceManager.GetString("IFCMVDBCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC2x3 Extended FM Handover View.
        /// </summary>
        public static string IFCMVDFMExtendedHandOver {
            get {
                return ResourceManager.GetString("IFCMVDFMExtendedHandOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC 2x3 Basic FM Handover View.
        /// </summary>
        public static string IFCMVDFMHandOver {
            get {
                return ResourceManager.GetString("IFCMVDFMHandOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC 2x3 GSA Concept Design BIM 2010.
        /// </summary>
        public static string IFCMVDGSA {
            get {
                return ResourceManager.GetString("IFCMVDGSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized file type option.
        /// </summary>
        public static string IFCUnknown {
            get {
                return ResourceManager.GetString("IFCUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC Version.
        /// </summary>
        public static string IFCVersion {
            get {
                return ResourceManager.GetString("IFCVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC 2x2 Coordination View.
        /// </summary>
        public static string IFCVersion2x2 {
            get {
                return ResourceManager.GetString("IFCVersion2x2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC 2x3 Coordination View.
        /// </summary>
        public static string IFCVersion2x3 {
            get {
                return ResourceManager.GetString("IFCVersion2x3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized IFC version.
        /// </summary>
        public static string IFCVersionUnrecognized {
            get {
                return ResourceManager.GetString("IFCVersionUnrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC XML.
        /// </summary>
        public static string IFCXML {
            get {
                return ResourceManager.GetString("IFCXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ifcxml.
        /// </summary>
        public static string IFCXMLExt {
            get {
                return ResourceManager.GetString("IFCXMLExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry Foundation Classes XML(.ifcxml)|*.ifcxml.
        /// </summary>
        public static string IFCXMLFiles {
            get {
                return ResourceManager.GetString("IFCXMLFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipped IFC XML.
        /// </summary>
        public static string IFCXMLZIP {
            get {
                return ResourceManager.GetString("IFCXMLZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ifczip.
        /// </summary>
        public static string IFCXMLZIPExt {
            get {
                return ResourceManager.GetString("IFCXMLZIPExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipped IFC.
        /// </summary>
        public static string IFCZIP {
            get {
                return ResourceManager.GetString("IFCZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ifczip.
        /// </summary>
        public static string IFCZIPExt {
            get {
                return ResourceManager.GetString("IFCZIPExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipped Industry Foundation Classes(.ifczip)|*.ifczip.
        /// </summary>
        public static string IFCZIPFiles {
            get {
                return ResourceManager.GetString("IFCZIPFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include IFCSITE elevation in the site local placement origin.
        /// </summary>
        public static string IncludeIfcSiteElevation {
            get {
                return ResourceManager.GetString("IncludeIfcSiteElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include space boundaries.
        /// </summary>
        public static string IncludeSpaceBoundaries {
            get {
                return ResourceManager.GetString("IncludeSpaceBoundaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;In-Session Setup&gt;.
        /// </summary>
        public static string InSessionConfiguration {
            get {
                return ResourceManager.GetString("InSessionConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal address.
        /// </summary>
        public static string InternalAddress {
            get {
                return ResourceManager.GetString("InternalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal location.
        /// </summary>
        public static string InternalLocation {
            get {
                return ResourceManager.GetString("InternalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create a temporary document for exporting the linked instance(s) for ids: {0}.
        /// </summary>
        public static string LinkInstanceExportCantCreateDoc {
            get {
                return ResourceManager.GetString("LinkInstanceExportCantCreateDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document for the linked instance(s) could not be found for ids: {0}..
        /// </summary>
        public static string LinkInstanceExportCantFindDoc {
            get {
                return ResourceManager.GetString("LinkInstanceExportCantFindDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} linked instance(s) could not be exported..
        /// </summary>
        public static string LinkInstanceExportErrorMain {
            get {
                return ResourceManager.GetString("LinkInstanceExportErrorMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path for the linked instance(s) did not exist for ids: {0}..
        /// </summary>
        public static string LinkInstanceExportErrorPath {
            get {
                return ResourceManager.GetString("LinkInstanceExportErrorPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The linked instance(s) were mirrored for ids: {0}.  To export a mirrored linked instance, mirror the linked geometry and link in the new document..
        /// </summary>
        public static string LinkInstanceExportHasReflection {
            get {
                return ResourceManager.GetString("LinkInstanceExportHasReflection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The linked instance(s) were non-conformal for ids: {0}..
        /// </summary>
        public static string LinkInstanceExportNonConformal {
            get {
                return ResourceManager.GetString("LinkInstanceExportNonConformal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The linked instance(s) were scaled for ids: {0}..
        /// </summary>
        public static string LinkInstanceExportScaled {
            get {
                return ResourceManager.GetString("LinkInstanceExportScaled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory fields Name, Source or Publisher, and Edition cannot be empty..
        /// </summary>
        public static string ManditoryFieldsNotEmpty {
            get {
                return ResourceManager.GetString("ManditoryFieldsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify setup ....
        /// </summary>
        public static string ModifySetup {
            get {
                return ResourceManager.GetString("ModifySetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New export setup.
        /// </summary>
        public static string NewExportSetup {
            get {
                return ResourceManager.GetString("NewExportSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name.
        /// </summary>
        public static string NewName {
            get {
                return ResourceManager.GetString("NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next....
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        public static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original name.
        /// </summary>
        public static string OriginalName {
            get {
                return ResourceManager.GetString("OriginalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase to export.
        /// </summary>
        public static string PhaseToExport {
            get {
                return ResourceManager.GetString("PhaseToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P. O. Box.
        /// </summary>
        public static string POBox {
            get {
                return ResourceManager.GetString("POBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export property sets.
        /// </summary>
        public static string PropertySets {
            get {
                return ResourceManager.GetString("PropertySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC common only.
        /// </summary>
        public static string PropertySetsIFCCommon {
            get {
                return ResourceManager.GetString("PropertySetsIFCCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC common, User-defined.
        /// </summary>
        public static string PropertySetsIFCCommonPlusUserDefined {
            get {
                return ResourceManager.GetString("PropertySetsIFCCommonPlusUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Revit only.
        /// </summary>
        public static string PropertySetsInternalRevit {
            get {
                return ResourceManager.GetString("PropertySetsInternalRevit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Revit, User-defined.
        /// </summary>
        public static string PropertySetsInternalRevitPlusUserDefined {
            get {
                return ResourceManager.GetString("PropertySetsInternalRevitPlusUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string PropertySetsNone {
            get {
                return ResourceManager.GetString("PropertySetsNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Revit, IFC common.
        /// </summary>
        public static string PropertySetsRevitPlusIFC {
            get {
                return ResourceManager.GetString("PropertySetsRevitPlusIFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Revit, IFC common, User-defined.
        /// </summary>
        public static string PropertySetsRevitPlusIFCPlusUserDefined {
            get {
                return ResourceManager.GetString("PropertySetsRevitPlusIFCPlusUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules only.
        /// </summary>
        public static string PropertySetsSchedules {
            get {
                return ResourceManager.GetString("PropertySetsSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC Common, Schedules.
        /// </summary>
        public static string PropertySetsSchedulesPlusIFC {
            get {
                return ResourceManager.GetString("PropertySetsSchedulesPlusIFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC Common, Schedules, User-defined.
        /// </summary>
        public static string PropertySetsSchedulesPlusIFCPlusUserDefined {
            get {
                return ResourceManager.GetString("PropertySetsSchedulesPlusIFCPlusUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Revit, Schedules.
        /// </summary>
        public static string PropertySetsSchedulesPlusRevit {
            get {
                return ResourceManager.GetString("PropertySetsSchedulesPlusRevit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Revit, IFC common, Schedules.
        /// </summary>
        public static string PropertySetsSchedulesPlusRevitPlusIFC {
            get {
                return ResourceManager.GetString("PropertySetsSchedulesPlusRevitPlusIFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Revit, IFC common, Schedules, User-defined.
        /// </summary>
        public static string PropertySetsSchedulesPlusRevitPlusIFCPlusUserDefined {
            get {
                return ResourceManager.GetString("PropertySetsSchedulesPlusRevitPlusIFCPlusUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Revit, Schedules, User-defined.
        /// </summary>
        public static string PropertySetsSchedulesPlusRevitPlusUserDefined {
            get {
                return ResourceManager.GetString("PropertySetsSchedulesPlusRevitPlusUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules, User-defined.
        /// </summary>
        public static string PropertySetsSchedulesPlusUserDefined {
            get {
                return ResourceManager.GetString("PropertySetsSchedulesPlusUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized property sets.
        /// </summary>
        public static string PropertySetsUnrecognized {
            get {
                return ResourceManager.GetString("PropertySetsUnrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-defined only.
        /// </summary>
        public static string PropertySetsUserDefined {
            get {
                return ResourceManager.GetString("PropertySetsUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose.
        /// </summary>
        public static string Purpose {
            get {
                return ResourceManager.GetString("Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename export setup.
        /// </summary>
        public static string RenameExportSetup {
            get {
                return ResourceManager.GetString("RenameExportSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename the selected setup..
        /// </summary>
        public static string RenameSelectedSetup {
            get {
                return ResourceManager.GetString("RenameSelectedSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Setup &amp;amp; Close.
        /// </summary>
        public static string SaveSetupAndClose {
            get {
                return ResourceManager.GetString("SaveSetupAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        public static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source file name.
        /// </summary>
        public static string SourceFileName {
            get {
                return ResourceManager.GetString("SourceFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source (Publisher).
        /// </summary>
        public static string SourcePublisher {
            get {
                return ResourceManager.GetString("SourcePublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space boundaries.
        /// </summary>
        public static string SpaceBoundaries {
            get {
                return ResourceManager.GetString("SpaceBoundaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st Level.
        /// </summary>
        public static string SpaceBoundaries1stLevel {
            get {
                return ResourceManager.GetString("SpaceBoundaries1stLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd Level.
        /// </summary>
        public static string SpaceBoundaries2ndLevel {
            get {
                return ResourceManager.GetString("SpaceBoundaries2ndLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string SpaceBoundariesNone {
            get {
                return ResourceManager.GetString("SpaceBoundariesNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized space boundary level.
        /// </summary>
        public static string SpaceBoundariesUnrecognized {
            get {
                return ResourceManager.GetString("SpaceBoundariesUnrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split walls and columns.
        /// </summary>
        public static string SplitWallsAndColumns {
            get {
                return ResourceManager.GetString("SplitWallsAndColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split walls and columns by level.
        /// </summary>
        public static string SplitWallsAndColumnsByLevel {
            get {
                return ResourceManager.GetString("SplitWallsAndColumnsByLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store the IFC GUID in an element parameter after export.
        /// </summary>
        public static string StoreIFCGUID {
            get {
                return ResourceManager.GetString("StoreIFCGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown alternate UI version.
        /// </summary>
        public static string UnkownAltUIVer {
            get {
                return ResourceManager.GetString("UnkownAltUIVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update IFC export setups.
        /// </summary>
        public static string UpdateExportSetups {
            get {
                return ResourceManager.GetString("UpdateExportSetups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update project address.
        /// </summary>
        public static string UpdateProjectAddress {
            get {
                return ResourceManager.GetString("UpdateProjectAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update project information.
        /// </summary>
        public static string UpdateProjectInformation {
            get {
                return ResourceManager.GetString("UpdateProjectInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use 2D room boundaries for room volume.
        /// </summary>
        public static string Use2DRoomBoundariesForRoomVolume {
            get {
                return ResourceManager.GetString("Use2DRoomBoundariesForRoomVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use coarse tessellation for some BReps.
        /// </summary>
        public static string UseCoarseTessellation {
            get {
                return ResourceManager.GetString("UseCoarseTessellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use coarse tessellation for some BReps and profiles.
        /// </summary>
        public static string UseCoarseTessellationForBReps {
            get {
                return ResourceManager.GetString("UseCoarseTessellationForBReps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use family and type name for reference.
        /// </summary>
        public static string UseFamilyAndTypeNameForReference {
            get {
                return ResourceManager.GetString("UseFamilyAndTypeNameForReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use family and type name for references.
        /// </summary>
        public static string UseFamilyAndTypeNameForReferences {
            get {
                return ResourceManager.GetString("UseFamilyAndTypeNameForReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined.
        /// </summary>
        public static string UserDefined {
            get {
                return ResourceManager.GetString("UserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom parameter sets.
        /// </summary>
        public static string UserDefinedParameterSets {
            get {
                return ResourceManager.GetString("UserDefinedParameterSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-defined purpose.
        /// </summary>
        public static string UserDefinedPurpose {
            get {
                return ResourceManager.GetString("UserDefinedPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use 2D room boundaries for room volume.
        /// </summary>
        public static string UseRoomBoundariesForRoomVolume {
            get {
                return ResourceManager.GetString("UseRoomBoundariesForRoomVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...value is set according to export option.
        /// </summary>
        public static string ValueSetByExportOption {
            get {
                return ResourceManager.GetString("ValueSetByExportOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...value will be set on export.
        /// </summary>
        public static string ValueSetOnExport {
            get {
                return ResourceManager.GetString("ValueSetOnExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version number.
        /// </summary>
        public static string VersionNumber {
            get {
                return ResourceManager.GetString("VersionNumber", resourceCulture);
            }
        }
    }
}
