//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIM.IFC.Export.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BIM.IFC.Export.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase to export.
        /// </summary>
        internal static string ActivePhase {
            get {
                return ResourceManager.GetString("ActivePhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default ({0}).
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Phase to export.
        /// </summary>
        internal static string DefaultPhase {
            get {
                return ResourceManager.GetString("DefaultPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export base quantities.
        /// </summary>
        internal static string ExportBaseQuantities {
            get {
                return ResourceManager.GetString("ExportBaseQuantities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export bounding box.
        /// </summary>
        internal static string ExportBoundingBox {
            get {
                return ResourceManager.GetString("ExportBoundingBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export IFC common property sets.
        /// </summary>
        internal static string ExportIFCCommonPropertySets {
            get {
                return ResourceManager.GetString("ExportIFCCommonPropertySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Linked Files as Separate IFCs.
        /// </summary>
        internal static string ExportLinkedFiles {
            get {
                return ResourceManager.GetString("ExportLinkedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export parts as building elements.
        /// </summary>
        internal static string ExportPartsAsBuildingElements {
            get {
                return ResourceManager.GetString("ExportPartsAsBuildingElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export plan view elements.
        /// </summary>
        internal static string ExportPlanViewElements {
            get {
                return ResourceManager.GetString("ExportPlanViewElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Revit property sets.
        /// </summary>
        internal static string ExportRevitPropertySets {
            get {
                return ResourceManager.GetString("ExportRevitPropertySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export schedules as property sets.
        /// </summary>
        internal static string ExportSchedulesAsPsets {
            get {
                return ResourceManager.GetString("ExportSchedulesAsPsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export solid models when possible.
        /// </summary>
        internal static string ExportSolidModelRep {
            get {
                return ResourceManager.GetString("ExportSolidModelRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export user-defined property sets.
        /// </summary>
        internal static string ExportUserDefinedPsets {
            get {
                return ResourceManager.GetString("ExportUserDefinedPsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export visible elements in view.
        /// </summary>
        internal static string ExportVisibleElementsInView {
            get {
                return ResourceManager.GetString("ExportVisibleElementsInView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type.
        /// </summary>
        internal static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File version.
        /// </summary>
        internal static string FileVersion {
            get {
                return ResourceManager.GetString("FileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC 2x3 Coordination View 2.0.
        /// </summary>
        internal static string IFCMVD2x3CV2 {
            get {
                return ResourceManager.GetString("IFCMVD2x3CV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC 4 Coordination View 2.0.
        /// </summary>
        internal static string IFCMVD4CV2 {
            get {
                return ResourceManager.GetString("IFCMVD4CV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC 2x2 Singapore BCA e-Plan Check.
        /// </summary>
        internal static string IFCMVDBCA {
            get {
                return ResourceManager.GetString("IFCMVDBCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC 2x3 Basic FM Handover View.
        /// </summary>
        internal static string IFCMVDFMHandOver {
            get {
                return ResourceManager.GetString("IFCMVDFMHandOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC 2x3 GSA Concept Design BIM 2010.
        /// </summary>
        internal static string IFCMVDGSA {
            get {
                return ResourceManager.GetString("IFCMVDGSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC 2x2 Coordination View.
        /// </summary>
        internal static string IFCVersion2x2 {
            get {
                return ResourceManager.GetString("IFCVersion2x2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC 2x3 Coordination View.
        /// </summary>
        internal static string IFCVersion2x3 {
            get {
                return ResourceManager.GetString("IFCVersion2x3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized IFCVersion.
        /// </summary>
        internal static string IFCVersionUnrecognized {
            get {
                return ResourceManager.GetString("IFCVersionUnrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include IFCSITE elevation in the site local placement origin.
        /// </summary>
        internal static string IncludeIfcSiteElevation {
            get {
                return ResourceManager.GetString("IncludeIfcSiteElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include space boundaries.
        /// </summary>
        internal static string IncludeSpaceBoundaries {
            get {
                return ResourceManager.GetString("IncludeSpaceBoundaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;In-Session Setup&gt;.
        /// </summary>
        internal static string InSessionConfiguration {
            get {
                return ResourceManager.GetString("InSessionConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export property sets.
        /// </summary>
        internal static string PropertySets {
            get {
                return ResourceManager.GetString("PropertySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC Common only.
        /// </summary>
        internal static string PropertySetsIFCCommon {
            get {
                return ResourceManager.GetString("PropertySetsIFCCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC Common, User Defined.
        /// </summary>
        internal static string PropertySetsIFCCommonPlusUserDefined {
            get {
                return ResourceManager.GetString("PropertySetsIFCCommonPlusUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Revit only.
        /// </summary>
        internal static string PropertySetsInternalRevit {
            get {
                return ResourceManager.GetString("PropertySetsInternalRevit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Revit, User Defined.
        /// </summary>
        internal static string PropertySetsInternalRevitPlusUserDefined {
            get {
                return ResourceManager.GetString("PropertySetsInternalRevitPlusUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string PropertySetsNone {
            get {
                return ResourceManager.GetString("PropertySetsNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Revit, IFC Common.
        /// </summary>
        internal static string PropertySetsRevitPlusIFC {
            get {
                return ResourceManager.GetString("PropertySetsRevitPlusIFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Revit, IFC Common, User Defined.
        /// </summary>
        internal static string PropertySetsRevitPlusIFCPlusUserDefined {
            get {
                return ResourceManager.GetString("PropertySetsRevitPlusIFCPlusUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules only.
        /// </summary>
        internal static string PropertySetsSchedules {
            get {
                return ResourceManager.GetString("PropertySetsSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC Common, Schedules.
        /// </summary>
        internal static string PropertySetsSchedulesPlusIFC {
            get {
                return ResourceManager.GetString("PropertySetsSchedulesPlusIFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFC Common, Schedules, User Defined.
        /// </summary>
        internal static string PropertySetsSchedulesPlusIFCPlusUserDefined {
            get {
                return ResourceManager.GetString("PropertySetsSchedulesPlusIFCPlusUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Revit, Schedules.
        /// </summary>
        internal static string PropertySetsSchedulesPlusRevit {
            get {
                return ResourceManager.GetString("PropertySetsSchedulesPlusRevit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Revit, IFC Common, Schedules.
        /// </summary>
        internal static string PropertySetsSchedulesPlusRevitPlusIFC {
            get {
                return ResourceManager.GetString("PropertySetsSchedulesPlusRevitPlusIFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Revit, IFC Common, Schedules, User Defined.
        /// </summary>
        internal static string PropertySetsSchedulesPlusRevitPlusIFCPlusUserDefined {
            get {
                return ResourceManager.GetString("PropertySetsSchedulesPlusRevitPlusIFCPlusUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Revit, Schedules, User Defined.
        /// </summary>
        internal static string PropertySetsSchedulesPlusRevitPlusUserDefined {
            get {
                return ResourceManager.GetString("PropertySetsSchedulesPlusRevitPlusUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules, User Defined.
        /// </summary>
        internal static string PropertySetsSchedulesPlusUserDefined {
            get {
                return ResourceManager.GetString("PropertySetsSchedulesPlusUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized property sets.
        /// </summary>
        internal static string PropertySetsUnrecognized {
            get {
                return ResourceManager.GetString("PropertySetsUnrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined only.
        /// </summary>
        internal static string PropertySetsUserDefined {
            get {
                return ResourceManager.GetString("PropertySetsUserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space boundaries.
        /// </summary>
        internal static string SpaceBoundaries {
            get {
                return ResourceManager.GetString("SpaceBoundaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st Level.
        /// </summary>
        internal static string SpaceBoundaries1stLevel {
            get {
                return ResourceManager.GetString("SpaceBoundaries1stLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd Level.
        /// </summary>
        internal static string SpaceBoundaries2ndLevel {
            get {
                return ResourceManager.GetString("SpaceBoundaries2ndLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string SpaceBoundariesNone {
            get {
                return ResourceManager.GetString("SpaceBoundariesNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized space boundary level.
        /// </summary>
        internal static string SpaceBoundariesUnrecognized {
            get {
                return ResourceManager.GetString("SpaceBoundariesUnrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split walls and columns.
        /// </summary>
        internal static string SplitWallsAndColumns {
            get {
                return ResourceManager.GetString("SplitWallsAndColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store the IFC GUID in an element parameter after export.
        /// </summary>
        internal static string StoreIFCGUID {
            get {
                return ResourceManager.GetString("StoreIFCGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use 2D room boundaries for room volume.
        /// </summary>
        internal static string Use2DRoomBoundariesForRoomVolume {
            get {
                return ResourceManager.GetString("Use2DRoomBoundariesForRoomVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use coarse tessellation for some BReps.
        /// </summary>
        internal static string UseCoarseTessellation {
            get {
                return ResourceManager.GetString("UseCoarseTessellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use family and type name for references.
        /// </summary>
        internal static string UseFamilyAndTypeNameForReferences {
            get {
                return ResourceManager.GetString("UseFamilyAndTypeNameForReferences", resourceCulture);
            }
        }
    }
}
